spring:
  datasource:
    #url: jdbc:mysql://47.93.184.21:36140/piggy_bank_test?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://47.93.184.21:36140/hupo_projects_example?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hupo123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
      filter:
        stat:
          enabled: true
      filters: stat